Manjaro Bootstrap - Security hardening script. Applies kernel sysctl, UFW firewall, AppArmor, auditd, and file permission hardening.

#!/bin/bash
################################################################################
# Manjaro Bootstrap - Security Hardening
# Author: skew202
# Description: Applies system security hardening (sysctl, firewall, etc.)
#
# Order: Run AFTER packages and services are installed
# Follow up with: sudo lynis audit system
################################################################################

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_step() { echo -e "\n${CYAN}═══ $1 ═══${NC}"; }

################################################################################
# KERNEL HARDENING
################################################################################

harden_kernel() {
    log_step "Kernel Hardening"

    sudo tee /etc/sysctl.d/99-security.conf > /dev/null << 'EOF'
# =============================================================================
# Security Hardening - sysctl configuration
# Generated by Manjaro Bootstrap Script
# =============================================================================

# -----------------------------------------------------------------------------
# Kernel pointers and memory protection
# -----------------------------------------------------------------------------
kernel.kptr_restrict = 2                    # Hide kernel pointers
kernel.dmesg_restrict = 1                   # Restrict dmesg to root
kernel.perf_event_paranoid = 2              # Restrict perf events
kernel.yama.ptrace_scope = 1                # Restrict ptrace (1 = restrict)
kernel.randomize_va_space = 2               # Full ASLR

# -----------------------------------------------------------------------------
# Core dumps
# -----------------------------------------------------------------------------
kernel.core_uses_pid = 1                    # Core dump filename includes PID
fs.suid_dumpable = 0                        # Prevent setuid core dumps

# -----------------------------------------------------------------------------
# Executable protection
# -----------------------------------------------------------------------------
fs.protected_regular = 2                    # Protected regular files
fs.protected_fifos = 2                      # Protected FIFOs
fs.protected_symlinks = 1                   # Protected symlinks
fs.protected_hardlinks = 1                  # Protected hardlinks

# -----------------------------------------------------------------------------
# Network hardening
# -----------------------------------------------------------------------------
# IP spoofing protection
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Ignore ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.secure_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# Ignore source routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# Log martians (packets with impossible addresses)
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# TCP hardening
net.ipv4.tcp_syncookies = 1                 # SYN cookies (SYN flood protection)
net.ipv4.tcp_rfc1337 = 1                    # Protect against TIME_WAIT attacks

# BPF hardening
kernel.unprivileged_bpf_disabled = 1        # Disable unprivileged BPF
net.core.bpf_jit_harden = 2                 # Harden BPF JIT compiler

# -----------------------------------------------------------------------------
# System stability
# -----------------------------------------------------------------------------
kernel.sysrq = 0                            # Disable SysRQ (magic system request key)
kernel.ctrl-alt-del = 0                     # Disable Ctrl+Alt+Del reboot

# -----------------------------------------------------------------------------
# Shared memory
# -----------------------------------------------------------------------------
kernel.shmmax = 68719476736                 # Max shared segment (64GB)
kernel.shmall = 4294967296                  # Max total shared memory (pages)
EOF

    # Apply settings
    sudo sysctl -p /etc/sysctl.d/99-security.conf

    log_success "Kernel hardening applied"
}

################################################################################
# FIREWALL CONFIGURATION
################################################################################

configure_firewall() {
    log_step "Firewall Configuration"

    if ! command -v ufw &>/dev/null; then
        log_warn "UFW not found. Install with: sudo pacman -S ufw"
        return
    fi

    # Set default policies
    sudo ufw default deny incoming
    sudo ufw default allow outgoing

    # Allow localhost
    sudo ufw allow from 127.0.0.1

    # Get local subnet (detect automatically)
    LOCAL_SUBNET=$(ip route get 1 2>/dev/null | grep -oP 'src \K\S+' | head -1 | sed 's/\.[0-9]*$/.0\/24/' || echo "192.168.0.0/24")

    log_info "Allowing local network: $LOCAL_SUBNET"
    sudo ufw allow from "$LOCAL_SUBNET"

    # Allow common services (uncomment if needed)
    # sudo ufw allow 22/tcp    # SSH
    # sudo ufw allow 80/tcp    # HTTP
    # sudo ufw allow 443/tcp   # HTTPS

    # Enable
    echo "y" | sudo ufw enable 2>/dev/null || true

    log_success "Firewall configured"
}

################################################################################
# APPARMOR
################################################################################

configure_apparmor() {
    log_step "AppArmor Configuration"

    if ! command -v aa-status &>/dev/null; then
        log_warn "AppArmor not found"
        return
    fi

    sudo systemctl enable apparmor.service
    sudo systemctl start apparmor.service

    # Check status
    if aa-status &>/dev/null; then
        log_success "AppArmor enabled and running"
    fi
}

################################################################################
# AUDITD
################################################################################

configure_auditd() {
    log_step "Audit Daemon Configuration"

    if ! command -v auditd &>/dev/null; then
        log_warn "auditd not found"
        return
    fi

    sudo systemctl enable auditd.service
    sudo systemctl start auditd.service

    log_success "auditd enabled"
}

################################################################################
# DISABLE UNUSED SERVICES
################################################################################

disable_unused_services() {
    log_step "Disabling Unused Services"

    # Services to consider disabling (comment out if you use them)
    local optional_services=(
        "cups.service"           # Printing
        "cups-browsed.service"   # Printer discovery
        "avahi-daemon.service"   # Network discovery (can leak hostname)
        "bluetooth.service"      # Bluetooth
    )

    for service in "${optional_services[@]}"; do
        if systemctl list-unit-files | grep -q "^$service"; then
            read -p "Disable $service? [y/N] " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                sudo systemctl disable "$service" 2>/dev/null || true
                sudo systemctl stop "$service" 2>/dev/null || true
                log_info "Disabled $service"
            fi
        fi
    done
}

################################################################################
# SECURE BOOT (OPTIONAL)
################################################################################

setup_secure_boot() {
    log_step "Secure Boot Setup"

    # Check if Secure Boot is available
    if ! mokutil --sb-state 2>/dev/null; then
        log_info "Secure Boot not available or not configured"
        log_info "To enable Secure Boot on Manjaro:"
        log_info "  1. Install: sudo pacman -S sbctl"
        log_info "  2. Enroll keys: sudo sbctl enroll-keys"
        return
    fi

    if mokutil --sb-state | grep -q "SecureBoot.*enabled"; then
        log_success "Secure Boot is enabled"
    else
        log_warn "Secure Boot is available but not enabled"
    fi
}

################################################################################
# GRUB HARDENING
################################################################################

harden_grub() {
    log_step "GRUB Hardening"

    # This is optional for personal machines
    # Uncomment if you need physical access protection

    # log_info "To protect GRUB with a password:"
    # log_info "  1. Run: grub-mkpasswd-pbkdf2"
    # log_info "  2. Add to /etc/grub.d/40_custom"
    # log_info "  3. Regenerate grub.cfg"

    log_info "GRUB password protection skipped (personal machine)"
}

################################################################################
# MALWARE SCANNER SETUP
################################################################################

setup_malware_scanner() {
    log_step "Malware Scanner Setup"

    # ClamAV
    if command -v clamscan &>/dev/null; then
        log_info "ClamAV installed"
        log_info "Enable freshclam timer: sudo systemctl enable --now clamav-freshclam.timer"
        log_info "Update database: sudo freshclam"
    fi

    # rkhunter
    if command -v rkhunter &>/dev/null; then
        log_info "rkhunter installed"
        log_info "Update: sudo rkhunter --update"
        log_info "Scan: sudo rkhunter --check"
    fi

    # chkrootkit
    if command -v chkrootkit &>/dev/null; then
        log_info "chkrootkit installed"
        log_info "Scan: sudo chkrootkit"
    fi
}

################################################################################
# FILE PERMISSIONS
################################################################################

harden_file_permissions() {
    log_step "File Permission Hardening"

    # Restrict cron directories
    sudo chmod 700 /etc/cron.{d,daily,hourly,monthly,weekly} 2>/dev/null || true

    # Restrict crontab
    sudo chmod 600 /etc/crontab 2>/dev/null || true

    # Restrict cron.deny
    sudo chmod 600 /etc/cron.deny 2>/dev/null || true

    log_success "File permissions hardened"
}

################################################################################
# SUMMARY
################################################################################

print_summary() {
    echo ""
    echo -e "${CYAN}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}Security hardening applied!${NC}"
    echo ""
    echo "Follow-up tasks:"
    echo "  1. Run security audit: sudo lynis audit system"
    echo "  2. Reboot to apply all kernel changes"
    echo "  3. Review firewall rules: sudo ufw status verbose"
    echo "  4. Check AppArmor: sudo aa-status"
    echo ""
    echo "Optional (higher security):"
    echo "  - Enable GRUB password (see script source)"
    echo "  - Setup file integrity monitoring (aide)"
    echo -e "${CYAN}═══════════════════════════════════════════════════════════${NC}"
}

################################################################################
# MAIN
################################################################################

main() {
    echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║              Security Hardening                           ║${NC}"
    echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"

    # Apply hardening
    harden_kernel
    configure_firewall
    configure_apparmor
    configure_auditd
    disable_unused_services
    setup_secure_boot
    harden_grub
    setup_malware_scanner
    harden_file_permissions

    print_summary
}

main "$@"
